#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons
CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEMS_DIR="$CONFIG_DIR/items"
FONT="JetBrains Mono"
source "$CONFIG_DIR/colors.sh" # Loads Rosé Pine colors

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
bar=(
  position=top
  height=32
  color=$BASE
  margin=240
  y_offset=8
  corner_radius=50
  padding_left=10
  padding_right=20

)

sketchybar --bar "${bar[@]}"
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  label.font="JetBrainsMono Nerd Font:Bold:13.0"
  icon.color=$TEXT
  label.color=$TEXT
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.height=28
  background.corner_radius=6
  popup.background.corner_radius=6
  popup.background.color=$SURFACE
  popup.background.border_color=$OVERLAY
  popup.background.border_width=2
)
sketchybar --default "${default[@]}"

#####AEROSPACE#####
# Minimal design: Only workspace indicators on the left

# Removed for minimal design:
# source "$CONFIG_DIR/items/power_menu.sh"

source "$CONFIG_DIR/items/aerospaces.sh"

# Removed for minimal design (spacer and front app):
# sketchybar --add item space_right_spaces left \
#   --set space_right_spaces \
#   label.padding_right=0 \
#   icon.drawing=off
#
# source "$CONFIG_DIR/items/front_app.sh"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

##### Adding Right Items #####
# Items

# sketchybar   --add item  ip_address right                              \
#            --set       ip_address script="$PLUGIN_DIR/ip_address.sh" \
#                                   update_freq=30                     \
#                                   padding_left=2                     \
#                                   padding_right=8                    \
#                                   background.border_width=0          \
#                                   background.corner_radius=6         \
#                                   background.height=24               \
#                                   icon.highlight=on                  \
#                                   label.highlight=on                 \
#            --subscribe ip_address wifi_change                        \
#            --add item  network.up right                              \
#            --set       network.up script="$PLUGIN_DIR/network.sh"    \
#                                   update_freq=20                     \
#                                   padding_left=2                     \
#                                   padding_right=2                    \
#                                   background.border_width=0          \
#                                   background.height=24               \
#                                   icon=⇡                             \
#                                   icon.color=$YELLOW                 \
#                                   label.color=$YELLOW                \
#            --add item  network.down right                            \
#            --set       network.down script="$PLUGIN_DIR/network.sh"  \
#                                update_freq=20                        \
#                                padding_left=8                        \
#                                padding_right=2                       \
#                                background.border_width=0             \
#                                background.height=24                  \
#                                icon=⇣                                \
#                                icon.color=$LOVE \
#                                label.color=$LOVE
#
# # Bracket
#

##### Adding Right Items #####
# Minimal design: WiFi, Bluetooth, Volume, Battery, Clock (with labels)

# Order matters: Items stack right-to-left, so source in reverse order
# Clock first = rightmost position
source "$CONFIG_DIR/items/clock.sh"
source "$CONFIG_DIR/items/battery.sh"
source "$CONFIG_DIR/items/volume.sh"
source "$CONFIG_DIR/items/bluetooth.sh"
source "$CONFIG_DIR/items/wifi.sh"

# Bracket for status icons (WiFi, Bluetooth, Volume, Battery)
sketchybar --add bracket status wifi bt volume battery \
  --set status \
  background.drawing=on \
  background.color=$OVERLAY \
  background.corner_radius=6 \
  background.height=24

# - System data (CPU, Memory, Disk)
# - System bracket

source "$CONFIG_DIR/items/system-data.sh"

sketchybar --update
sketchybar --hotload true
